// Package config manages the skillvendor lockfile at
// ~/.config/skillvendor/skillvendor.lock. The lock pins each manifest entry
// to a resolved commit SHA so `sync` is reproducible across machines and
// across time even when the manifest ref is a moving branch.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mattjmcnaughton/skillvendor/internal/paths"
	"gopkg.in/yaml.v3"
)

const LockVersion = 1

// LockEntry pins a single (repo, path) manifest entry to a SHA and records
// which skills were installed from it at that revision.
type LockEntry struct {
	Repo      string   `yaml:"repo"`
	Path      string   `yaml:"path,omitempty"`
	Ref       string   `yaml:"ref"`
	SHA       string   `yaml:"sha"`
	Installed []string `yaml:"installed,omitempty"`
}

func (e LockEntry) Key() string {
	if e.Path == "" {
		return e.Repo
	}
	return e.Repo + "#" + e.Path
}

type Lock struct {
	Version int         `yaml:"version"`
	Entries []LockEntry `yaml:"entries"`

	path string
}

// DefaultPath returns ~/.config/skillvendor/skillvendor.lock. Honors SKILLVENDOR_HOME.
func DefaultPath() (string, error) {
	home, err := paths.Home()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "skillvendor", "skillvendor.lock"), nil
}

// Load reads the lockfile. A missing file returns an empty lock (not an error).
func Load(path string) (*Lock, error) {
	l := &Lock{Version: LockVersion, path: path}
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return l, nil
		}
		return nil, err
	}
	if err := yaml.Unmarshal(data, l); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if l.Version != 0 && l.Version != LockVersion {
		return nil, fmt.Errorf("unsupported lockfile version %d (want %d)", l.Version, LockVersion)
	}
	l.Version = LockVersion
	return l, nil
}

func (l *Lock) Save() error {
	if l.path == "" {
		return errors.New("lock path is empty")
	}
	if err := os.MkdirAll(filepath.Dir(l.path), 0o755); err != nil {
		return err
	}
	data, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	body := append([]byte("# Auto-generated by skillvendor. Do not edit by hand.\n"), data...)
	tmp, err := os.CreateTemp(filepath.Dir(l.path), ".skillvendor.*.lock")
	if err != nil {
		return err
	}
	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(tmp.Name())
		return err
	}
	return os.Rename(tmp.Name(), l.path)
}

func (l *Lock) Path() string { return l.path }

// Find returns the index of the entry matching repo+path, or -1.
func (l *Lock) Find(repo, path string) int {
	for i, e := range l.Entries {
		if e.Repo == repo && e.Path == path {
			return i
		}
	}
	return -1
}

// Get returns the locked entry for repo+path, if any.
func (l *Lock) Get(repo, path string) (LockEntry, bool) {
	i := l.Find(repo, path)
	if i < 0 {
		return LockEntry{}, false
	}
	return l.Entries[i], true
}

// Upsert inserts or replaces a lock entry by (repo, path).
func (l *Lock) Upsert(e LockEntry) {
	if i := l.Find(e.Repo, e.Path); i >= 0 {
		l.Entries[i] = e
		return
	}
	l.Entries = append(l.Entries, e)
}

// Remove drops the entry matching repo+path. Returns false if not found.
func (l *Lock) Remove(repo, path string) bool {
	i := l.Find(repo, path)
	if i < 0 {
		return false
	}
	l.Entries = append(l.Entries[:i], l.Entries[i+1:]...)
	return true
}
